[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/api/medium"
  to = "/.netlify/functions/api-medium"
  status = 200

[[redirects]]
  from = "/api/linkedin/experience"
  to = "/.netlify/functions/api-linkedin-experience"
  status = 200

[[redirects]]
  from = "/api/linkedin/skills"
  to = "/.netlify/functions/api-linkedin-skills"
  status = 200

[[redirects]]
  from = "/endurance"
  to = "/endurance.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200